name: whitepine
favicon: null
layout_spectrum: 0.7671259136404842
typography_spectrum: 0.7657549844589084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f8320'
    - '#6a92d0'
    - '#5aa92e'
    - '#dbe7d5'
  brandStrength: 0.625
  lightness: 0.8391374668572098
  saturation: 0.5581095907837152
  rhythmicContrast: 0.495197556912899
purpose: []
